set quiet := true

# set aliases

self := justfile_directory()
export TYPST_ROOT := self

[private]
default:
    @just --list --unsorted

# generate manual
doc:
    typst compile docs/docs.typ docs/docs.pdf

test module:
    @echo "Starting tests for Module: {{ module }}..."
    typst compile "tests/test-{{ module }}.typ"
    @echo "Test {{ module }} passed!"

test-all:
    @echo "Running all tests..."
    just test assignments
    just test scenarios
    just test questions
    @echo "All tests passed!"

pack:
    chase pack . @preview --overwrite
